export const endpoints = {
    'booking_order'               : 'booking/booking',
    'booking_engine_operator'     : 'booking/engine/operator',
    'booking_engine_airport'      : 'booking/engine/airport',
    'booking_tour'                : 'booking/tour/tour',
    'booking_tour_period'         : 'booking/tour/period',
    'booking_halal'               : 'booking/halal/hotel',
    'member_list'                 : 'crm/customer',
    'subscriber_list'             : 'crm/subscriber',
    'ecommerce_regions'           : 'region/country',
    'user'                        : 'sys/user/user',
    'user_groups'                 : '/sys/user/group',
    'design_menu'                 : 'design/menu/menu',
    'localization_language'       : 'sys/language',
    'localization_currency'       : 'sys/currency',
    'setting'                     : 'sys/settings/settings/get-by-category',
    'setting_category'            : 'sys/settings/category',
    "link"                        : 'sys/link',
    "log"                         : 'sys/log',
    "log"                         : 'sys/domain',
    "campaign_promo"              : "marketing/coupon",
    "campaign_affilate"           : "marketing/affilate",
    "campaign_affilatelink"       : "marketing/affilatelink",
	'content_post'                : 'content/post/post',
    'content_post_category'       : 'content/post/category',
    'content_page'                : 'content/page',
    'module_branch'               : 'crm/branch',
    'content_support'             : 'content/support/support',
    'content_support_category'    : 'content/support/category',
    'homepage_seo_text'           : 'content/homepage/seo-text',
    'homepage_seo_link'           : 'content/homepage/seo-link',
    'block_favourite'             : 'block/favourite',
    'block_tab'                   : 'block/tab',
    'landing_otel'                : 'landing/otel',
    'landing_zone'                : 'landing/zone',
    'landing_base'                : 'landing/base',
    'landing_footer'              : 'landing/footer',
    'tour_tab'                    : 'tour/tab',
    'tour_type'                    :'booking/tour/type',
    'ecommerce_payment'            : 'payment'


}
